-- ====================================================================
-- IoMT Security Shield - Database Schema (PostgreSQL/Supabase DDL)
-- Copy and paste this script directly into your Supabase SQL Editor.
-- ====================================================================

-- --------------------------------------------------
-- 1. Create logs table (For storing telemetry events and security decisions)
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp timestamptz NOT NULL DEFAULT now(),
  "deviceId" text NOT NULL,
  "heartRate" integer NOT NULL,
  decision text NOT NULL,
  reason text NOT NULL,
  stage text NOT NULL,
  "reachedHospitalServer" boolean NOT NULL DEFAULT false,
  "gatewayId" text NOT NULL DEFAULT 'GW-EDGE-01',
  "requestOrigin" text NOT NULL DEFAULT '127.0.0.1',
  "dbProtectionType" text NOT NULL DEFAULT 'Isolated (No Write)'
);

-- Indexing for fast dashboard queries
CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON public.logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_logs_device ON public.logs("deviceId");
CREATE INDEX IF NOT EXISTS idx_logs_decision ON public.logs(decision);

-- --------------------------------------------------
-- 2. Row Level Security (RLS) for logs Table
-- Allows secure public select and inserts for our IoMT demonstration gateway.
-- --------------------------------------------------
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert" ON public.logs;
CREATE POLICY "Allow public insert" 
  ON public.logs FOR INSERT 
  TO anon 
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select" ON public.logs;
CREATE POLICY "Allow public select" 
  ON public.logs FOR SELECT 
  TO anon 
  USING (true);


-- --------------------------------------------------
-- 3. Create profiles table (Stores extended user profile data)
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  email text UNIQUE NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  organization text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'Analyst',
  bio text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- RLS Policies for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);


-- --------------------------------------------------
-- 4. Triggers and Helper Functions
-- --------------------------------------------------

-- A. Auto-update updated_at timestamp on profile change
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

-- B. Automatically create a profile row when a new user registers (Supabase Auth Link)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.email, '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();
